1147 sveikatos priežiūros įstaigų licencijų duomenys duomenys apie sveikatos priežiūros įstaigų licencijas veiklos adresus ir teikiamas sveikatos priežiūros paslaugas
atviriduomenys/manifest pull request #1387
Opened 2022-04-04 12:25 UTC by DaumantasJauga

2022-04-05 19:03 UTC, sirex requested changes

2022-04-05 19:03 UTC, sirex commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,Licencijos_,,,,,,,,,Licencijos,
```suggestion
,,,,Licencija,,,,,,,,,Licencijos,

```

2022-04-05 19:03 UTC, sirex commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,IstaiguVeikluAdresai,,,,,,,,,Sveikatos priežiūros įstaigų veiklos adresai,
```suggestion
,,,,IstaigosVeiklosAdresas,,,,,,,,,Sveikatos priežiūros įstaigų veiklos adresai,

```

2022-04-05 19:03 UTC, sirex commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,LaboratoriniaiTyrimai,,,,,,,,,Laboratoriniai tyrimai,
```suggestion
,,,,LaboratorinisTyrimas,,,,,,,,,Laboratoriniai tyrimai,
```

2022-04-05 19:03 UTC, sirex commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,VeiklosAdresuPaslaugos,,,,,,,,,Veiklos adresų paslaugos,
```suggestion
,,,,VeiklosAdresoPaslauga,,,,,,,,,Veiklos adresų paslaugos,
```

2022-04-06 17:57 UTC, sirex reviewed
Laukų pavadinimai neatitinka [reikalavimų](https://atviriduomenys.readthedocs.io/dsa/kodiniai-pavadinimai.html). Gal galima būtų pakeisti pagal pasiūlymus?

Kitose vietose, panašu, kad ne visur sudėti ryšiai tarp modelių.

2022-04-06 17:57 UTC, sirex commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,,sudarymo_data,date,,,,3,open,,Licencijos išdavimo data,
```suggestion
,,,,,sudaryta,date,,,,3,open,,Licencijos išdavimo data,
```
Sudaryta ar išduota?

2022-04-06 17:57 UTC, sirex commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,,panaikinimo_data,date,,,,3,open,,Licencijos panaikinimo data ,
```suggestion
,,,,,panaikinta,date,,,,3,open,,Licencijos panaikinimo data ,

```

2022-04-06 17:57 UTC, sirex commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,,isakymo_id,ref,Isakymas,,,4,open,,Įsakymo identifikatorius,
```suggestion
,,,,,isakymas,ref,Isakymas,,,4,open,,Įsakymas,
```

2022-04-06 17:57 UTC, sirex commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,,filialo_id,string,,,,4,open,,Filialo identifikatorius,
```suggestion
,,,,,id,string,,,,4,open,,Filialo identifikatorius,
```

2022-04-06 17:57 UTC, sirex commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,,filialo_pavadinimas,string,,,,2,open,,Filialo pavadinimas,
```suggestion
,,,,,pavadinimas,string,,,,2,open,,Filialo pavadinimas,
```

2022-04-06 17:57 UTC, sirex commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,,spi_id,ref,Istaiga,,,4,open,,Sveikatos priežiūros įstaigos identifikatorius,
```suggestion
,,,,,istaiga,ref,Istaiga,,,4,open,,Sveikatos priežiūros įstaigos identifikatorius,
```

2022-04-06 17:57 UTC, sirex commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,,paslaugos_id,string,,,,2,open,,Paslaugos identifikatorius,
```suggestion
,,,,,paslauga,ref,IstaigosPaslauga,,,2,open,,Paslauga,
```
?

2022-04-06 17:57 UTC, sirex commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,,istaigos_paslaugos_profilio_id,string,,,,2,open,,Paslaugos profilio identifikatorius,
```suggestion
,,,,,profilis,ref,IstaigosPaslauguProfilis,,,2,open,,Paslaugos profilis,
```
?

2022-04-06 17:57 UTC, sirex commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,,istaigos_paslaugos_id,string,,,,2,open,,Paslaugos identifikatorius,
```suggestion
,,,,,paslauga,ref,IstaigosPaslauga,,,2,open,,Paslauga,
```
?

2022-04-06 17:57 UTC, sirex commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,VWPilnaAdresoInfo,,,,,,,,,Adresai ,
```suggestion
,,,,Adresas,,,,,,,,,Adresas,
```

2022-04-07 11:53 UTC, DaumantasJauga commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,,adreso_id,string,,,,4,open,,Adreso identifikatorius,
taip, visus identifikatorius verčiame į string

2022-04-07 11:55 UTC, DaumantasJauga commented on datasets/gov/vaspvt/licencijos.csv
> +,,,,,paslaugos_id,string,,,,2,open,,Paslaugos identifikatorius,
Nepridėjau daugiau sąryšių nei buvo gautą iš institucijos

2022-04-11 07:49 UTC, sirex approved these changes

2022-04-11 07:49 UTC, merged