pvm_deklaracijos.csv
atviriduomenys/manifest pull request #1394
Opened 2022-04-07 13:33 UTC by DataAIchemist

2022-04-08 12:11 UTC, IngaIVPK requested changes

2022-04-08 13:00 UTC, sirex requested changes
Kaip suprantu, čia yra Abby FormFiller pagrindu sudarytų formų, statistiniai duomenys?

Mes lyg ir sutarėm, kad visi nauji duomenų rinkiniai bus [SDMX](https://sdmx.org/), [DDI](https://ddialliance.org/) ar bent [SD pačių susigalvotu duomenų mainų standartu](https://estatistika.stat.gov.lt/apie-estatistika/duomenu-mainu-standartas.html)?

Šioje vietoje sumaišyti skirtingų rūšių objektai:

- formos metaduomenys
- dimensijos
- klasifikatoriai, kurie kaip suprantu nepateikti
- formos klausimai (prarandant formoje esančias sekcijas, numeravimą ir kitus metaduomenis)
- rodikliai

Panaši situacija aprašyta čia: https://github.com/atviriduomenys/manifest/pull/941#issuecomment-1072440184

Tam, kad didinti tokio pobūdžio pakartotinį pernaudojamumą, siūlau prisilaikyti standartų?

2022-04-08 13:00 UTC, sirex commented on datasets/gov/vmi/pvm_deklaracijos.csv
> +,,,,,11_pvm_apmokestinami_sandoriai,number,,,,3,open,,"PVM apmokestinami tiekimai (18, 9, 5 procentais)",
```suggestion
,,,,,pvm_apmokestinami_sandoriai,number,,,,3,open,,"PVM apmokestinami tiekimai (18, 9, 5 procentais)",
```

Pavadinimai negali prasidėti skaičiumi, [dokumentacijoje](https://atviriduomenys.readthedocs.io/dsa/kodiniai-pavadinimai.html) būtent prie laukų tai nepaminėta, bet tas galioja ir laukams.

Tas pats ir kitose vietose.

2022-04-11 08:07 UTC, DataAIchemist commented on datasets/gov/vmi/pvm_deklaracijos.csv
> +,,,,,sekcija_pagal_ekonomines_veiklos_rusiu_klasifikatoriu,string,,,,3,open,,"Deklaracijoje nurodyta pagrindinė vykdomos veiklos rūšis pagal Ekonominės veiklos rūšių klasifikatorių, patvirtintą Stati
EVRK sekcija parašytas tokia forma: "A. Žemės ūkis, miškininkystė ir žuvininkystė" (t.y. atstovo pageidavimu pridėta klasifikatoriaus reikšmė iškart duomenų rinkinyje su tikslu, kad vartotojams  būtų lengviau naviguoti). Ar tokiu atveju vis tiek reikėtų "enum" pridėti papildomai?

2022-04-11 08:09 UTC, DataAIchemist commented on datasets/gov/vmi/pvm_deklaracijos.csv
> +,,,,,skyrius_pagal_ekonomines_veiklos_rusiu_klasifikatoriu,string,,,,3,open,,"Pagrindinė vykdomos veiklos rūšis pagal EVRK. Imama iš klasifikatoriaus, jei pavyko identifikuoti pagal deklaracijoje įra
EVRk skyrius parašytas taip pat tokia forma: "A01. Augalininkystė ir gyvulininkystė, medžioklė ir susijusių paslaugų veikla"

2022-04-11 08:10 UTC, DataAIchemist commented on datasets/gov/vmi/pvm_deklaracijos.csv
> +,,,,,11_pvm_apmokestinami_sandoriai,number,,,,3,open,,"PVM apmokestinami tiekimai (18, 9, 5 procentais)",
> jeigu atskirai pateikiami sandoriai apmokesdinami 18, 9, 5 procentais, ar tuomet nereikia `enum`?

Nepateikiami atskirai. Tai yra sumos, eurais.

2022-04-11 08:40 UTC, DataAIchemist commented on datasets/gov/vmi/pvm_deklaracijos.csv
> +,,,,,sekcija_pagal_ekonomines_veiklos_rusiu_klasifikatoriu,string,,,,3,open,,"Deklaracijoje nurodyta pagrindinė vykdomos veiklos rūšis pagal Ekonominės veiklos rūšių klasifikatorių, patvirtintą Stati
Pritaikytas konfidencialumas, todėl tai nėra standartinė klasifikatoriaus forma, nes yra reikšmė "nenustatyta". Užsiimančių ta pačia veikla mokesčių mokėtojų dominavimo atveju nėra nustatyta EVRK sekcija, EVRK skyrius ir apskritis

2022-04-11 09:31 UTC, DataAIchemist commented
> Kaip suprantu, čia yra Abby FormFiller pagrindu sudarytų formų, statistiniai duomenys?
> 
> Mes lyg ir sutarėm, kad visi nauji duomenų rinkiniai bus [SDMX](https://sdmx.org/), [DDI](https://ddialliance.org/) ar bent [SD pačių susigalvotu duomenų mainų standartu](https://estatistika.stat.gov.lt/apie-estatistika/duomenu-mainu-standartas.html)?
> 
> Šioje vietoje sumaišyti skirtingų rūšių objektai:
> 
> * formos metaduomenys
> * dimensijos
> * klasifikatoriai, kurie kaip suprantu nepateikti
> * formos klausimai (prarandant formoje esančias sekcijas, numeravimą ir kitus metaduomenis)
> * rodikliai
> 
> Panaši situacija aprašyta čia: [#941 (comment)](https://github.com/atviriduomenys/manifest/pull/941#issuecomment-1072440184)
> 
> Tam, kad didinti tokio pobūdžio pakartotinį pernaudojamumą, siūlau prisilaikyti standartų?

Čia ne statistiniai duomenys, o agreguoti VMI mikroduomenys. Klasifikatoriaus sekcija (taip pat ir skyrius) parašytas su kodu A, B, C ir kt. bei lietuviška prasme. Pvz. A. Žemės ūkis, miškininkystė ir žuvininkystė

2022-04-11 11:23 UTC, IngaIVPK requested changes

2022-04-11 11:23 UTC, IngaIVPK commented on datasets/gov/vmi/pvm_deklaracijos.csv
> +,,,,,mokestinis_laikotarpis,datetime,M,,,4,open,,Mokestinis laikotarpis iki (laikotarpio pabaigos data),
```suggestion
,,,,,mokestinis_laikotarpis,date,M,,,4,open,,Mokestinis laikotarpis iki (laikotarpio pabaigos data),
```
Plačiau: https://atviriduomenys.readthedocs.io/dsa/duomenu-tipai.html

2022-04-11 11:23 UTC, IngaIVPK commented on datasets/gov/vmi/pvm_deklaracijos.csv
> +,,,,,sekcija_pagal_ekonomines_veiklos_rusiu_klasifikatoriu,string,,,,3,open,,"Deklaracijoje nurodyta pagrindinė vykdomos veiklos rūšis pagal Ekonominės veiklos rūšių klasifikatorių, patvirtintą Stati
Jeigu duomenys koduoti (A, B, C ir pan.), rekomenduojame naudoti `enum`

2022-04-11 11:23 UTC, IngaIVPK commented on datasets/gov/vmi/pvm_deklaracijos.csv
> +,,,,,skyrius_pagal_ekonomines_veiklos_rusiu_klasifikatoriu,string,,,,3,open,,"Pagrindinė vykdomos veiklos rūšis pagal EVRK. Imama iš klasifikatoriaus, jei pavyko identifikuoti pagal deklaracijoje įra
žr. į 6 eil. naują komentarą

2022-04-11 12:43 UTC, DataAIchemist commented on datasets/gov/vmi/pvm_deklaracijos.csv
> +,,,,,sekcija_pagal_ekonomines_veiklos_rusiu_klasifikatoriu,string,,,,3,open,,"Deklaracijoje nurodyta pagrindinė vykdomos veiklos rūšis pagal Ekonominės veiklos rūšių klasifikatorių, patvirtintą Stati
Ne, nurodytas ne tik kodas. Žymimas kodas + prasmė t.y. pvz. A. Žemės ūkis, miškininkystė ir žuvininkystė

2022-04-11 12:57 UTC, DataAIchemist commented on datasets/gov/vmi/pvm_deklaracijos.csv
> +,,,,,apskritis,string,,,,3,open,,Deklaracijai priskirtos apskrities pavadinimas,"Užsiimančių ta pačia veikla mokesčių mokėtojų dominavimo atveju nėra nustatyta EVRK sekcija, EVRK skyrius ir apskritis
Tai nėra apskrities kodas, o pavadinimas, tad ar tikrai tinka toks modifikavimas? Matau, jog nurodyta tik į model Apskritis, kurio pirminis raktas yra adm_kodas.

2022-04-11 13:12 UTC, DataAIchemist commented on datasets/gov/vmi/pvm_deklaracijos.csv
> +,,,,,skyrius_pagal_ekonomines_veiklos_rusiu_klasifikatoriu,string,,,,3,open,,"Pagrindinė vykdomos veiklos rūšis pagal EVRK. Imama iš klasifikatoriaus, jei pavyko identifikuoti pagal deklaracijoje įra
Ne, nurodytas ne tik kodas. Žymimas kodas + prasmė t.y. pvz. A01. Augalininkystė ir gyvulininkystė, medžioklė ir susijusių paslaugų veikla.

2022-04-11 13:17 UTC, DataAIchemist commented on datasets/gov/vmi/pvm_deklaracijos.csv
> +,,,,,mokestinis_laikotarpis,datetime,M,,,4,open,,Mokestinis laikotarpis iki (laikotarpio pabaigos data),
Duomenys yra datetime (laikas šaltinyje yra). Ref stupelyje mėginau rašyti "YYY-MM", tačiau tiko tik "M".

2022-04-13 07:56 UTC, closed without merging