Ekonominės veiklos rūšių klasifikatorius
atviriduomenys/manifest pull request #1457
Opened 2022-05-11 10:40 UTC by Marius-prog

2022-05-11 14:41 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,datasets/gov/lsd/klasifikatoriai,,,,,,,,,,,,Statistikos departamento klasifikatoriai,
```suggestion
,datasets/gov/lsd/klasifikatoriai/veiklos,,,,,,,,,,,,Ekonominės veiklos klasifikatorius,

```

2022-05-11 14:42 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,datasets/gov/lsd/klasifikatoriai,,,,,,,,,,,,Statistikos departamento klasifikatoriai,
Failo pavadinimas nesutampa su vardų erdvės pavadinimu.

2022-05-12 07:57 UTC, sirex requested changes
Reikėtų visose vietose pataisyti:

- [x] Pavadinimai ir sakiniai pradedami didžiąja raide.
- [x] Visur, kur yra tas pats atributas pateikiamas skirtingomis kalbomis, rašoma vienodą atributo pavadinimą ir pridedame kalbos sufiksą `_en` arba `_lt` ir žymime tokius atributus `2` brandos lygiu, nes tipas turėtu būti ne `string`, o `text`, tačiau `text` dar nėra palaikomas: https://github.com/atviriduomenys/spinta/issues/204.
- [ ] Panašu, kad po `description` atsirado dar vienas tuščias stulpelis, reikėtų jį panaikinti.

2022-05-12 07:57 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,datasets/gov/lsd/klasifikatoriai/veiklos,,,,,,,,,,,,Statistikos departamento klasifikatoriai,Ekonominės veiklos rūšies klasifikatorius,
```suggestion
,datasets/gov/lsd/klasifikatoriai/veiklos,,,,,,,,,,,,Ekonominės veiklos rūšies klasifikatorius,
```

„Statistikos departamento klasifikatoriai“ turėtu būti nurodytas prie `datasets/gov/lsd/klasifikatoriai`.

2022-05-12 07:57 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,lygmens_pavadinimas,string,,,,3,open,,lygmens pavadinimas,,
```suggestion
,,,,,pavadinimas_lt,string,,,,3,open,,Pavadinimas,,
```
- Atributuose nedubliuojamas modelio pavadinimas.
- Pavadinimai užrašomi iš didžiosios raidės.
- https://github.com/atviriduomenys/spinta/issues/204

2022-05-12 07:57 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,level_name,string,,,,3,open,,lygmens pavadinimo vertimas,,
```suggestion
,,,,,pavadinimas_en,string,,,,3,open,,Pavadinimas,,
```

Natūralios kalbos atributai turėtu būti `text` tipo, ir užrašomi `pavadinimas@en`, `pavadinmias@lt`, bet kol kas tai neįgyvendinta:

- https://github.com/atviriduomenys/spinta/issues/204

Todėl reikėtų atributo pavadinimus išlaikyti vienodus, prirašant kalbos kodą kaip `_en` prefiksą.

2022-05-12 07:57 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,lygmuo,integer,,,,3,open,,lygmuo,,
```suggestion
,,,,,lygmuo,integer,,,,3,open,,Lygmuo,,
```

Pavadinimai užrašomi iš didžiosios raidės.

2022-05-12 07:57 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,pavadinimas,string,,,,3,open,,lygmens kodo pavadinimas,,
```suggestion
,,,,,pavadinimas_lt,string,,,,3,open,,Pavadinimas,,
```

2022-05-12 07:57 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,description,string,,,,3,open,,lygmens kodo pavadinimo vertimas ,,
```suggestion
,,,,,pavadinimas_lt,string,,,,3,open,,Pavadinimas,,
```

2022-05-12 07:57 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,aiskinamosios_pastabos,string,,,,3,open,,pastabos,,
```suggestion
,,,,,pastabos_lt,string,,,,2,open,,Aiškinamosios pastabos,,
```

2022-05-12 07:57 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,explanatory_notes,string,,,,3,open,,pastabos vertimas,,
```suggestion
,,,,,pastabos_en,string,,,,2,open,,Aiškinamosios pastabos,,
```

- https://github.com/atviriduomenys/spinta/issues/204

2022-05-12 07:57 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,ankstesnis_kodas,ref,EkonominesVeiklosRusis,,,4,open,,ankstesnė lygmens kodo versija,,
```suggestion
,,,,,bendresne_veiklos_rusis,ref,EkonominesVeiklosRusis,,,4,open,skos:broader,Ankstesnė lygmens kodo versija,,
```

- Remiantis [SKOS](https://www.w3.org/TR/skos-reference/#semantic-relations), siūlau pavadinimą keisti į „bendresne_veiklos_rusis“. SOKS tai vadina `broader`, todėl galima iš esmės tai įtraukti į URI, tik reikia nepamiršti įtraukti ir `skos` [prefiksą](https://atviriduomenys.readthedocs.io/dsa/dimensijos.html#isoriniu-zodynu-prefiksai) `http://www.w3.org/2004/02/skos/core#`.
-  Pavadinimai užrašomi iš didžiosios raidės.

2022-05-12 11:25 UTC, sirex requested changes
- [ ] Reikia pataisyti failų pavadinimus, kad sutaptu su vardų erdvės pavadinimais.
- [ ] Panašu, kad po description atsirado dar vienas tuščias stulpelis, reikėtų jį panaikinti.
- [ ] Pataisyti brandos lygius.
- [ ] Prefiksas turi būti įrašytas į atskirą eilutę.

2022-05-12 11:25 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,datasets/gov/lsd/klasifikatoriai/veiklos,,,,,prefix,,,,,,http://www.w3.org/2004/02/skos/core#,Statistikos departamento klasifikatoriai,Ekonominės veiklos rūšies klasifikatorius,
Failo pavadinimas nesutampa su vardų erdvės pavadinimu. reikia keisti failo pavadinimą.

2022-05-12 11:25 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,datasets/gov/lsd/klasifikatoriai/veiklos,,,,,prefix,,,,,,http://www.w3.org/2004/02/skos/core#,Statistikos departamento klasifikatoriai,Ekonominės veiklos rūšies klasifikatorius,
```suggestion
,,,,,,prefix,skos,,,,,http://www.w3.org/2004/02/skos/core#,,,
,,,,,,,,,,,,,,,
,datasets/gov/lsd/klasifikatoriai/veiklos,,,,,,,,,,,,Ekonominės veiklos klasifikatorius,,
```

URI prefiksai įrašomi atskiroje eilutėje.

2022-05-12 11:25 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,pavadinimas_lt,string,,,,3,open,,Pavadinimas,,
```suggestion
,,,,,pavadinimas_lt,string,,,,2,open,,Pavadinimas,,
```

2022-05-12 11:25 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,pavadinimas_en,string,,,,3,open,,Pavadinimas,,
```suggestion
,,,,,pavadinimas_en,string,,,,2,open,,Pavadinimas,,
```

2022-05-12 11:25 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,lygmuo,integer,,,,3,open,,Lygmuo,,
```suggestion
,,,,,lygmuo,integer,,,,4,open,,Lygmuo,,
```

2022-05-12 11:25 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,pavadinimas_lt,string,,,,3,open,,Pavadinimas,,
```suggestion
,,,,,pavadinimas_lt,string,,,,2,open,,Pavadinimas,,
```

2022-05-12 11:25 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,kodas,string,,,,3,open,,Lygmens kodas,,
```suggestion
,,,,,kodas,string,,,,2,open,,Lygmens kodas,,
```

2022-05-12 11:25 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,pavadinimas_en,string,,,,3,open,,Pavadinimas,,
```suggestion
,,,,,pavadinimas_en,string,,,,2,open,,Pavadinimas,,
```

2022-05-12 11:25 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,bendresne_veiklos_rusis,ref,EkonominesVeiklosRusis,,,4,open,skos:broader,Ankstesnė lygmens kodo versija,,
```suggestion
,,,,,bendresne_veiklos_rusis,ref,EkonominesVeiklosRusis,,,5,open,skos:broader,Ankstesnė lygmens kodo versija,,
```

2022-05-12 13:57 UTC, sirex requested changes

2022-05-12 13:57 UTC, sirex commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,,,,,,prefix,skos,,,,,http://www.w3.org/2004/02/skos/core#,,,
Sorry, klaidingai nurodžiau, `prefix` eilutė turi eiti žemiau duomenų rinkinio eilutės. Atskiriems rinkiniams negalima apibrėžti globalių prefiksų.

2022-05-12 14:27 UTC, Marius-prog commented on datasets/gov/lsd/ekonominis_veiklos_rusies_klasifikatorius.csv
> +,datasets/gov/lsd/klasifikatoriai,,,,,,,,,,,,Ekonominės veiklos klasifikatorius,,
tai 6iuo atveju turi būti failo pavadinimas klasifikatoriai_evrk.csv ?

2022-05-12 18:02 UTC, merged