1231 žemėlapių nomenkltūrinių lapų tinkleliai
atviriduomenys/manifest pull request #1493
Opened 2022-06-08 11:46 UTC by DataAIchemist

2022-06-09 10:08 UTC, IngaIVPK requested changes

2022-06-09 12:25 UTC, IngaIVPK requested changes
Pateikti pasiūlymai tik `model` `LKS94500`, tačiau pagal juos patikslinimus reikėtų atlikti visame ADSA.

2022-06-09 12:25 UTC, IngaIVPK commented on datasets/gov/giscentras/nomenklatura.csv
> +,,,,,nom1k,string,,,,3,open,,NOM1K,Žemėlapio lapo numeris pagal žemėlapio nomenklatūrinį skaidymą lapais masteliu 1:1 000 LKS-94 koordinačių sistemoje
```suggestion
,,,,,nom1k,string,,,,4,open,,NOM1K,Žemėlapio lapo numeris pagal žemėlapio nomenklatūrinį skaidymą lapais masteliu 1:1 000 LKS-94 koordinačių sistemoje

```
Siūlomas `level` pakeitimas, atsižvelgiant į tai, jeigu tai nekeičiamas laukas su unikalia reikšme.

2022-06-10 08:27 UTC, DataAIchemist commented on datasets/gov/giscentras/nomenklatura.csv
> +,,,,,nom5k,string,,,,3,open,,NOM5K,Žemėlapio lapo numeris pagal žemėlapio nomenklatūrinį skaidymą lapais masteliu 1:5 000 LKS-94 koordinačių sistemoje
Tai keičiamas laukas

2022-06-13 19:48 UTC, sirex commented
Kadangi aprašomi duomenys yra sintetiniai, gan prasto brandos lygio ir jau publikuojami, kaip atviri duomenys, siūlau jų nepublikuoti get.data.gov.lt (pašalinau eilutę iš `get_data_gov_lt.in`.

2022-06-14 07:04 UTC, merged