2843 ekvivalentinių disponuojamųjų pajamų gini koeficientas
atviriduomenys/manifest pull request #2844
Opened 2023-12-14 09:50 UTC by hishonor13

2023-12-14 13:19 UTC, Folkas requested changes

2023-12-14 13:19 UTC, Folkas commented on datasets/gov/lsd/statistika/gini_koeficientas.csv
> +,,,,S3R0283_M3080313,,,vda_id,,,4,,,Ekvivalentinių disponuojamųjų pajamų Gini koeficientas,"Pateikta statistinė informacija apie Lietuvos Respublikos negyvų gimusių kūdikių skaičių pagal gyvenamąją v
manrods, description'as iš seno rinkinio paliktas, tai jį reikia atnaujinti

2023-12-15 07:04 UTC, hishonor13 commented on datasets/gov/lsd/statistika/gini_koeficientas.csv
> +,,,,S3R0283_M3080313,,,vda_id,,,4,,,Ekvivalentinių disponuojamųjų pajamų Gini koeficientas,"Pateikta statistinė informacija apie Lietuvos Respublikos negyvų gimusių kūdikių skaičių pagal gyvenamąją v
nežinau kaip susimaišė, bet pataisyta

2023-12-15 07:51 UTC, Folkas approved these changes

2023-12-15 07:53 UTC, merged