2847 metinis užimtumo lygis pagal tikslines amžiaus grupes ir lytį
atviriduomenys/manifest pull request #2848
Opened 2023-12-14 10:06 UTC by hishonor13

2023-12-14 13:46 UTC, Folkas requested changes

2023-12-14 13:46 UTC, Folkas commented on datasets/gov/lsd/statistika/metinis_uzimtumo_lygis.csv
> +,,,,,amzius_5_m_amziaus_grupes,string,,,,4,open,,Amžius (5 m. amžiaus grupės),
čia irgi sutrumpink stulpelio pavadinimą. Stulpelio pavadinimas turi susidėti iš max 2-3 žodžių. Čia gali rašyti amziaus_grupes ar pan.

2023-12-14 13:46 UTC, Folkas commented on datasets/gov/lsd/statistika/metinis_uzimtumo_lygis.csv
> +,,,,,amzius_5_m_amziaus_grupes,string,,,,4,open,,Amžius (5 m. amžiaus grupės),
visa kita yra gerai

2023-12-15 06:24 UTC, hishonor13 commented on datasets/gov/lsd/statistika/metinis_uzimtumo_lygis.csv
> +,,,,,amzius_5_m_amziaus_grupes,string,,,,4,open,,Amžius (5 m. amžiaus grupės),
pataisyta

2023-12-15 07:46 UTC, Folkas approved these changes

2023-12-15 07:46 UTC, merged