3148 vdaus vandens keli direkcija vvkd
atviriduomenys/manifest pull request #3150
Opened 2024-03-12 11:31 UTC by hishonor13

2024-03-12 14:41 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,geometry,geometry(3857),,,,3,,,Geometrijos tipas,
Čia ir toliau - geometry galima nurodyti 4 brandos lygį.

2024-03-12 14:46 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,atstumas,number,km,,,4,,,Atstumas,
Stulpelio aprašymo lauke title norėtųsi, kad būtų tiksliau nurodytas atstumo apibrėžimas.

2024-03-12 14:48 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,pav,string,,,,4,,,Pavadinimas,
Papildomai reikės papildyti stulpelio pavadinimą prefiksu "_lt", kad ateityje stulpelis būtų interpretuojamas kaip text tipo.

2024-03-12 14:51 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,name,string,,,,3,,,Pavadinimas,
Kaip ir aukščiau - siūlyčiau pridėti prie stulpelio pavadinimo prefiksą "_lt", atitinkamai brandos lygis 4.

2024-03-12 14:52 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,notes,string,,,,3,,,Pastabos,
Kaip ir aukščiau - siūlyčiau pridėti prie stulpelio pavadinimo prefiksą "_lt", atitinkamai brandos lygis 4.

2024-03-12 14:52 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,x,string,,,,3,,,x koordinatė,
Čia ir žemiau, siūlyčiau nurodyti "number" tipą, tada brandos lygis bus 4.

2024-03-12 14:55 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,angle,number,,,,3,,,Sutartinio ženklo pasūkimo kampas,
Siūlyčiau nurodyti matavimo vienetus laipsnius, tada atitinkamai brandos lygis būtų 4.

2024-03-12 15:00 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,notes,string,,,,4,,,Pastabos,
Kaip ir aukščiau - siūlyčiau pridėti prie stulpelio pavadinimo prefiksą "_lt", atitinkamai brandos lygis 4.

2024-03-12 15:00 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,angle,number,,,,3,,,Sutartinio ženklo pasūkimo kampas,
Tas pats kaip auščiau - nurodyti matavimo vienetus laispnius, ir atitinkamai brandos lygis 4.

2024-03-12 15:00 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,ObjektaiEdit,,,objectid,,,4,,,Objektų informacija,Šiame sluoksnyje pateikiama objektų informacija. Objektai išdėstyti Nemune bei Minijoje.
Modelio pavadinimas turėtų būti vienaskaitos forma.

2024-03-12 15:03 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,papildomainfo,string,,,,3,,,Papildoma informacija,
Kaip ir aukščiau - siūlyčiau pridėti prie stulpelio pavadinimo prefiksą "_lt", atitinkamai brandos lygis 4.

2024-03-12 15:04 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,created_user,string,,,,2,,,Sukūrimo vartotojas,
Siūlyčiau stulpelio atsiakyti - reikšmės asmenų vardai ir pavardės, daug naudos neneša stulpelis.

2024-03-12 15:05 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,last_edited_user,string,,,,2,,,Paskutinis koregavimo vartotojas,
Siūlyčiau stulpelio atsisakyti - reikšmės asmenų vardai ir pavardės, daug naudos neneša ir brandos lygis žemas.

2024-03-12 15:06 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,last_edited_date,date,L,,,4,,,Paskutinė koregavimo data,
Duomenų rinkinyje dar vis matau UNIX reikšmę.

2024-03-12 15:10 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,konstr,string,,,,4,,,Bunos konstrukcijos tipas,
Siūlyčiau su enum pavardinti konstrukcijos tipus.

2024-03-12 15:12 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,info,string,,,,4,,,Informacija,
Kaip ir aukščiau - siūlyčiau pridėti prie stulpelio pavadinimo prefiksą "_lt", atitinkamai brandos lygis 4.

2024-03-12 15:19 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,pav,string,,,,4,,,Pavadinimas,
Kadangi yra daug įvairių reikšmių, siūlyčiau brandos lygį nurodyti 2, nes nėra vieningo formato.

2024-03-12 15:19 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,info,string,,,,4,,,Informacija,
Kaip ir aukščiau - siūlyčiau pridėti prie stulpelio pavadinimo prefiksą "_lt", atitinkamai brandos lygis 4.

2024-03-12 15:22 UTC, AugusteSkre commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,pavadinim,string,,,,4,,,Pavadinimas,
Kadangi yra daug įvairių reikšmių, siūlyčiau brandos lygį nurodyti 2, nes nėra vieningo formato.

2024-03-12 15:24 UTC, AugusteSkre requested changes
Pakeitimų siūlymai nurodyti komentaruose.

2024-03-13 11:12 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,geometry,geometry(3857),,,,3,,,Geometrijos tipas,
Pakeista į 4 brandos lygį.

2024-03-13 11:41 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,pav,string,,,,4,,,Pavadinimas,
Pataisyta

2024-03-13 11:45 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,name,string,,,,3,,,Pavadinimas,
Atlikta

2024-03-13 11:46 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,notes,string,,,,3,,,Pastabos,
Atlikta

2024-03-13 12:08 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,angle,number,,,,3,,,Sutartinio ženklo pasūkimo kampas,
Atlikta

2024-03-13 12:09 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,notes,string,,,,4,,,Pastabos,
Atlikta

2024-03-13 12:10 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,angle,number,,,,3,,,Sutartinio ženklo pasūkimo kampas,
Atlikta

2024-03-13 12:12 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,info,string,,,,4,,,Informacija,
Atlikta

2024-03-13 12:14 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,papildomainfo,string,,,,3,,,Papildoma informacija,
Atlikta

2024-03-13 12:17 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,last_edited_date,date,L,,,4,,,Paskutinė koregavimo data,
Po duomenų valymo commito patvirtinimo bus sutvarkyta

2024-03-14 07:20 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,konstr,string,,,,4,,,Bunos konstrukcijos tipas,
Atlikta

2024-03-14 07:22 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,info,string,,,,4,,,Informacija,
Atlikta

2024-03-14 07:23 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,pav,string,,,,4,,,Pavadinimas,
Atlikta

2024-03-14 07:23 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,info,string,,,,4,,,Informacija,
Atlikta

2024-03-14 09:30 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,x,string,,,,3,,,x koordinatė,
Pakeista

2024-03-14 09:41 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,ObjektaiEdit,,,objectid,,,4,,,Objektų informacija,Šiame sluoksnyje pateikiama objektų informacija. Objektai išdėstyti Nemune bei Minijoje.
Atlikta

2024-03-14 09:47 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,created_user,string,,,,2,,,Sukūrimo vartotojas,
Pašalinta

2024-03-14 09:48 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,last_edited_user,string,,,,2,,,Paskutinis koregavimo vartotojas,
Pašalinta

2024-03-14 09:48 UTC, hishonor13 commented on datasets/gov/vvkd/e_zemelapiai.csv
> +,,,,,konstr,string,,,,4,,,Bunos konstrukcijos tipas,
Atlikta

2024-03-14 12:44 UTC, AugusteSkre approved these changes

2024-03-14 13:14 UTC, merged