3574 skiepijimų duomenys
atviriduomenys/manifest pull request #3575
Opened 2024-09-04 11:13 UTC by ZygimantasB1

skiepų švieslentės data atvėrimui,
pridėjau vda_id stulpelį, bei pakeičiau a2 lauką, kad atitiktu vietą spintoje

2024-09-04 12:21 UTC, dovileer requested changes

2024-09-04 12:21 UTC, dovileer commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,,,,SkiepytiGripo,,,vda_id,,,,,,Asmenys,"paskiepyti šaltojo sezono skiepais, pagal ligą, įstaigą, lytį ir amžiaus grupę"
```suggestion
,,,,SkiepytiGripo,,,vda_id,,,,,,"Asmenys, paskiepyti šaltojo sezono skiepais, pagal ligą, įstaigą, lytį ir amžiaus grupę",

```

2024-09-04 12:21 UTC, dovileer commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,,,,,liga,string,,,,2,open,,Liga,nuo kurios skiepijama
```suggestion
,,,,,liga,string,,,,2,open,,"Liga, nuo kurios skiepijama",

```

2024-09-04 12:21 UTC, dovileer commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,,,,,liga,string,,,,2,open,,Liga,nuo kurios skiepijama
```suggestion
,,,,,liga,string,,,,2,open,,"Liga, nuo kurios skiepijama"

```

2024-09-04 12:21 UTC, dovileer commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,,,,,n_asm,integer,,,,4,open,,Skaičius asmenų,paskiepytų nuo tos ligos tą dieną
```suggestion
,,,,,n_asm,integer,,,,4,open,,"Skaičius asmenų, paskiepytų nuo tos ligos tą dieną",

```

2024-09-04 12:21 UTC, dovileer commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,,,,SkiepytiVakcina,,,vda_id,,,,,,Pasiskiepiję asmenys pagal laikotarpį,"ligą, vakciną ir įstaigą"
```suggestion
,,,,SkiepytiVakcina,,,vda_id,,,,,,"Pasiskiepiję asmenys pagal laikotarpį, ligą, vakciną ir įstaigą",

```

2024-09-04 12:21 UTC, dovileer commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,,,,,liga,string,,,,2,open,,Liga,nuo kurios skiepijama
```suggestion
,,,,,liga,string,,,,2,open,,"Liga, nuo kurios skiepijama",

```

2024-09-04 12:21 UTC, dovileer commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,,,,,medication_name,string,,,,2,open,,Vakcinos,"kuria skiepijama, pavadinimas"
```suggestion
,,,,,medication_name,string,,,,2,open,,"Vakcinos, kuria skiepijama, pavadinimas",

```

2024-09-04 12:21 UTC, dovileer commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,,,,,n_asm_istaigoje,integer,,,,4,open,,Asmenų skaičius pagal ligą,vakciną ir įstaigą
```suggestion
,,,,,n_asm_istaigoje,integer,,,,4,open,,"Asmenų skaičius pagal ligą, vakciną ir įstaigą",

```

2024-09-04 12:21 UTC, dovileer commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,,,,,n,integer,,,,4,open,,Asmenų skaičius,"Skaičius nurodyto amžiaus ir lyties asmenų, paskiepytų toje įstaigoje nurodytu laikotarpiu, nuo nurodytos ligos. Skaičiuojami unikalūs asmenys įstaigos ir l
Ar čia turėtų būti "n_asm", kaip ir kitose vietose?
```suggestion
,,,,,n_asm,integer,,,,4,open,,Asmenų skaičius,"Skaičius nurodyto amžiaus ir lyties asmenų, paskiepytų toje įstaigoje nurodytu laikotarpiu, nuo nurodytos ligos. Skaičiuojami unikalūs asmenys įstaigos ir laikotarpio lygiu, taigi asmuo gali būti įtrauktas į šią lentelę kelis kartus, jei skiepijosi skirtingose įstaigose, o taip pat viso sezono skaičius gali būti mažesnis nei visų mėnesių skaičių suma"

```

2024-09-04 12:36 UTC, ZygimantasB1 commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,,,,,n,integer,,,,4,open,,Asmenų skaičius,"Skaičius nurodyto amžiaus ir lyties asmenų, paskiepytų toje įstaigoje nurodytu laikotarpiu, nuo nurodytos ligos. Skaičiuojami unikalūs asmenys įstaigos ir l
pagal lentelę tai turėtu būti "n"

2024-09-04 13:11 UTC, dovileer approved these changes

2024-09-04 13:20 UTC, jjuod commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,,,,SkiepytiGripo,,,vda_id,,,,,,"Asmenys, paskiepyti šaltojo sezono skiepais, pagal ligą, įstaigą, lytį ir amžiaus grupę",
,,,,SkiepytiGripo,,,vda_id,,,,,,"Asmenys, paskiepyti šaltojo sezono ligų (gripo) skiepais, pagal ligą (gripas), įstaigą lytį ir amžiaus grupę",Kol kas pateikti tik gripo duomenys

2024-09-04 14:06 UTC, dovileer commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,datasets/gov/lsd/sveikata/skiepai,,,,,,,,,,,,,
Čia taip pat galima įrašyti pavadinimą, kad matytųsi prie folderio pavadinimo saugykloje
```suggestion
,datasets/gov/lsd/sveikata/skiepai,,,,,,,,,,,,"Asmenys, paskiepyti šaltojo sezono skiepais, pagal ligą, įstaigą, lytį ir amžiaus grupę",

```

2024-09-04 14:32 UTC, jjuod commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,datasets/gov/lsd/sveikata/skiepai,,,,,,,,,,,,,
čia Julius. tada siūlau "Asmenys, paskiepyti įvairių ligų skiepais", nes ten skirtingos lentelės skirtingai agreguotos

2024-09-04 14:48 UTC, ZygimantasB1 commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,datasets/gov/lsd/sveikata/skiepai,,,,,,,,,,,,,
done

2024-09-05 07:26 UTC, dovileer commented on datasets/gov/lsd/sveikata/skiepai.csv
> +,,,,,date,date,D,,,4,open,,Diena,kurią skiepyta
```suggestion
,,,,,date,date,D,,,4,open,,"Diena, kurią skiepyta",

```

2024-09-05 07:34 UTC, merged